"""Stage 1: fine-grained keyphrase -> column retrieval.

Input  (profiles/): dev.json, dev_tables.json
Output (results/):  question_keywords.json
                    question_keywords_top{N}_columns.json
                    column_embeddings.pt / column_ids.json / column_meta.json
                    keyword_embeddings.pt / unique_keywords.json

Two sub-steps:

  1. An LLM decomposes each question into non-composite noun concepts and
     attributes ("keyphrases"). Cached in question_keywords.json and written
     after every question, so an interrupted run resumes for free.
  2. Every column of the collection is embedded as "TABLE_NAME COLUMN_NAME"
     with a sentence encoder, every keyphrase is embedded the same way, and
     the top-N most similar columns per keyphrase are stored. Both embedding
     sets are cached, so re-running without --force-* costs nothing.

Only sub-step 1 calls an LLM; sub-step 2 runs locally on CPU, MPS or CUDA.

Run:
    python -m table_discovery.column_retrieval --dataset Beaver-Prep --top-k 100
"""

from __future__ import annotations

import argparse
import os
import re
from typing import Any, Dict, List

import numpy as np
import torch
import torch.nn.functional as F
from tqdm import tqdm
from transformers import AutoModel, AutoTokenizer

from common import paths as P
from common.io_utils import create_directory, read_json, write_json, write_json_atomic
from common.llm_client import llm_generate


# ============================================================
# Prompt for keyword/concept extraction
# ============================================================

COTD_FEW_SHOT = """I'm going to ask you a question. I want you to decompose it into a series of non-composite noun concepts and attributes. If you are uncertain about concepts, only output attributes. You should wrap each concept and attribute in <sub_c></sub_c> tags. Once you have all the concepts you need to cover the question, output <FIN></FIN> tags.

Follow these rules strictly:
1. PRESERVE every modifier/qualifier that appears in the question. Do NOT generalize. For example, keep "HR department name" as is — do NOT shorten it to "department name". Keep "gross square footage", "assignable area", "facility organization" with their modifiers.
2. Use the form entity:attribute ONLY when the entity that OWNS the attribute is explicitly named in the question. Do NOT prepend the entity that is merely the subject being queried, a container, or the context. For "the organization name of each room", output "organization:name", NOT "room:organization name". For "the square footage of rooms", output "room:square footage", but for "total square footage" with no owner, output just "square footage".
3. Never convert a mentioned entity into an aggregate or a count. Counts, totals, numbers-of, and averages are OPERATIONS, not concepts. If the question says "the organizations occupying them" or "number of organizations", output the concept "organizations" — NOT "organization:count" or "building:number of organizations".
4. When the question already gives a clean noun phrase for the concept, output that noun phrase faithfully rather than re-bucketing it under an unrelated entity.

Let's go through some examples together. Do you understand the instructions?

Assistant: Yes, I understand. I will decompose questions into faithful noun concepts and attributes, preserve all qualifiers, only use entity:attribute when the owning entity is explicitly named, and never turn a mentioned entity into a count/aggregate. I'll wrap each component in <sub_c></sub_c> tags and finish with <FIN></FIN>.

Human: Question: For movies with the keyword of \"civil war\", calculate the average revenue generated by these movies.

Assistant:
<sub_c>movies:keyword</sub_c>
<sub_c>movies:revenue</sub_c>
<FIN></FIN>

Human: Question: How many customers have a credit limit of not more than 100,000 and which customer made the highest total payment amount for the year 2004?

Assistant:
<sub_c>customers:credit limit</sub_c>
<sub_c>customers:payment amount</sub_c>
<sub_c>year</sub_c>
<FIN></FIN>

Human: Question: What is the aircraft name for the flight with number 99?
Assistant:
<sub_c>aircraft:name</sub_c>
<sub_c>flight:number</sub_c>
<FIN></FIN>

Human: Question: List the building names and the HR department name occupying them, and the number of organizations per building.
Assistant:
<sub_c>building:name</sub_c>
<sub_c>HR department name</sub_c>
<sub_c>organizations</sub_c>
<FIN></FIN>

Human: Question: For each room, show its organization name, the floor number, and the total square footage.
Assistant:
<sub_c>organization:name</sub_c>
<sub_c>floor number</sub_c>
<sub_c>square footage</sub_c>
<FIN></FIN>

Human: Question: What is the id of the trip that started from the station with the highest dock count?
Assistant:
<sub_c>trip:id</sub_c>
<sub_c>station:dock count</sub_c>
<FIN></FIN>
"""


# ============================================================
# Basic IO
# ============================================================
# ============================================================

def build_keyword_extraction_prompt(question: str) -> str:
    return f"""{COTD_FEW_SHOT}

Human: Question: {question}

Assistant:
""".strip()


def parse_sub_concepts(llm_output: str) -> List[str]:
    """
    Extract contents inside <sub_c>...</sub_c>.
    """
    concepts = re.findall(r"<sub_c>(.*?)</sub_c>", llm_output, flags=re.DOTALL)
    concepts = [c.strip() for c in concepts if c.strip()]

    # remove duplicates while preserving order
    seen = set()
    unique_concepts = []
    for c in concepts:
        key = c.lower()
        if key not in seen:
            seen.add(key)
            unique_concepts.append(c)

    return unique_concepts


def extract_keywords_for_dev(
    dev: List[Dict[str, Any]],
    out_path: str,
    model: str = "gpt-4.1",
    force_regenerate: bool = False,
):
    """
    Extract keywords/concepts for each question in dev.json.
    Save after each question to avoid losing progress.
    """
    if os.path.exists(out_path) and not force_regenerate:
        question_keywords = read_json(out_path)
        print(f"Loaded existing keyword extraction from: {out_path}")
    else:
        question_keywords = {}

    for q_idx, item in enumerate(tqdm(dev, desc="Extracting question keywords")):
        question = item["question"]
        qid = str(item.get("question_id", item.get("id", q_idx)))

        if not force_regenerate and qid in question_keywords:
            continue

        prompt = build_keyword_extraction_prompt(question)
        output = llm_generate(prompt, model=model)
        keywords = parse_sub_concepts(output)

        question_keywords[qid] = {
            "question_id": qid,
            "question": question,
            "keywords": keywords,
            "raw_output": output,
        }

        write_json_atomic(question_keywords, out_path)

    return question_keywords


# ============================================================
# Build column-level corpus
# ============================================================

def normalize_column_name(col):
    """
    Handle different possible column formats.
    Usually your dev_tables.json uses a list of strings.
    """
    if col is None:
        return ""

    if isinstance(col, str):
        return col

    # In some Spider-like formats, a column could be [table_idx, column_name]
    if isinstance(col, (list, tuple)):
        if len(col) == 0:
            return ""
        return str(col[-1])

    return str(col)


def build_column_corpus(tables: Dict[str, Dict[str, Any]]):
    """
    Each column is represented by table name + column name.

    Return:
      column_ids: unique column ids
      column_texts: texts for embedding
      column_meta: metadata for saving results
    """
    column_ids = []
    column_texts = []
    column_meta = []

    for table_id, table in tables.items():
        table_name = (
            table.get("table_name_original")
            or table.get("table_name")
            or table_id
        )

        cols = table.get("column_names_original", [])

        for col_idx, col in enumerate(cols):
            col_name = normalize_column_name(col)

            if not col_name:
                continue

            # skip Spider-style wildcard column if exists
            if col_name == "*":
                continue

            column_id = f"{table_id}::{col_name}"

            # Core design: column text = table name + column name
            column_text = f"{table_name} {col_name}"

            column_ids.append(column_id)
            column_texts.append(column_text)
            column_meta.append({
                "column_id": column_id,
                "table_id": table_id,
                "table_name": table_name,
                "column_name": col_name,
                "column_index": col_idx,
                "embedding_text": column_text,
            })

    return column_ids, column_texts, column_meta


# ============================================================
# UAE embedding
# ============================================================

def mean_pooling(token_embeddings: torch.Tensor, mask: torch.Tensor) -> torch.Tensor:
    token_embeddings = token_embeddings.masked_fill(~mask[..., None].bool(), 0.0)
    return token_embeddings.sum(dim=1) / mask.sum(dim=1)[..., None]


def embed_texts(
    texts: List[str],
    model_name: str = "WhereIsAI/UAE-Large-V1",
    batch_size: int = 64,
    device: str = None,
) -> torch.Tensor:
    if device is None:
        # Prefer CUDA, then Apple Silicon (MPS), then CPU. The encoder is small
        # enough that CPU is also workable for a single collection.
        if torch.cuda.is_available():
            device = "cuda"
        elif getattr(torch.backends, "mps", None) is not None and torch.backends.mps.is_available():
            device = "mps"
        else:
            device = "cpu"
    print(f"[embed] device={device} texts={len(texts)}")

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModel.from_pretrained(model_name).to(device)
    model.eval()

    all_embeds = []

    for i in tqdm(range(0, len(texts), batch_size), desc="Embedding"):
        batch = texts[i:i + batch_size]

        inputs = tokenizer(
            batch,
            padding=True,
            truncation=True,
            max_length=512,
            return_tensors="pt",
        ).to(device)

        with torch.no_grad():
            outputs = model(**inputs)
            vec = mean_pooling(outputs[0], inputs["attention_mask"])
            vec = F.normalize(vec, p=2, dim=1)

        all_embeds.append(vec.cpu())

    return torch.cat(all_embeds, dim=0)


def get_or_build_column_embeddings(
    tables: Dict[str, Dict[str, Any]],
    out_dir: str,
    model_name: str = "WhereIsAI/UAE-Large-V1",
    batch_size: int = 64,
    force_recompute: bool = False,
):
    embedding_path = f"{out_dir}/column_embeddings.pt"
    column_ids_path = f"{out_dir}/column_ids.json"
    column_meta_path = f"{out_dir}/column_meta.json"

    if (
        os.path.exists(embedding_path)
        and os.path.exists(column_ids_path)
        and os.path.exists(column_meta_path)
        and not force_recompute
    ):
        print(f"Loading column embeddings from: {embedding_path}")
        column_embeds = torch.load(embedding_path, map_location="cpu")
        column_ids = read_json(column_ids_path)
        column_meta = read_json(column_meta_path)
        return column_ids, column_meta, column_embeds

    print("Building column-level corpus...")

    # Default setting: only use table name + column name as embedding text.
    # This does NOT require column_descriptions.json.
    column_ids, column_texts, column_meta = build_column_corpus(tables)

    # If you later want to include sampled values or generated column descriptions,
    # uncomment the following block and make sure column_descriptions.json exists.
    # column_descriptions = read_json(f"{desc_dir}/column_descriptions.json")
    # column_ids, column_texts, column_meta = build_enriched_column_corpus(
    #     tables,
    #     column_descriptions,
    #     mode="name_values_desc",  # or "name_values"
    # )


    print(f"Number of columns: {len(column_ids)}")

    column_embeds = embed_texts(
        column_texts,
        model_name=model_name,
        batch_size=batch_size,
    )

    create_directory(out_dir)
    torch.save(column_embeds, embedding_path)
    write_json(column_ids, column_ids_path)
    write_json(column_meta, column_meta_path)

    print(f"Saved column embeddings to: {embedding_path}")
    print(f"Saved column ids to: {column_ids_path}")
    print(f"Saved column meta to: {column_meta_path}")

    return column_ids, column_meta, column_embeds


# ============================================================
# Keyword-column retrieval
# ============================================================

def collect_unique_keywords(question_keywords: Dict[str, Dict[str, Any]]) -> List[str]:
    keywords = []
    seen = set()

    for qid, rec in question_keywords.items():
        for kw in rec.get("keywords", []):
            key = kw.lower().strip()
            if key and key not in seen:
                seen.add(key)
                keywords.append(kw.strip())

    return keywords


def retrieve_topk_columns_for_keywords(
    question_keywords: Dict[str, Dict[str, Any]],
    column_meta: List[Dict[str, Any]],
    column_embeds: torch.Tensor,
    out_dir: str,
    model_name: str = "WhereIsAI/UAE-Large-V1",
    batch_size: int = 64,
    top_k: int = 30,
    force_recompute_keyword_embeddings: bool = False,
):
    """
    For each extracted keyword, search top-k most similar columns.
    Save column-level similarity scores.
    """
    keyword_emb_path = f"{out_dir}/keyword_embeddings.pt"
    keyword_list_path = f"{out_dir}/unique_keywords.json"

    unique_keywords = collect_unique_keywords(question_keywords)

    if (
        os.path.exists(keyword_emb_path)
        and os.path.exists(keyword_list_path)
        and not force_recompute_keyword_embeddings
    ):
        print(f"Loading keyword embeddings from: {keyword_emb_path}")
        saved_keywords = read_json(keyword_list_path)
        keyword_embeds = torch.load(keyword_emb_path, map_location="cpu")

        # If keyword set changed, recompute.
        if saved_keywords != unique_keywords:
            print("Keyword list changed. Recomputing keyword embeddings...")
            keyword_embeds = embed_texts(
                unique_keywords,
                model_name=model_name,
                batch_size=batch_size,
            )
            torch.save(keyword_embeds, keyword_emb_path)
            write_json(unique_keywords, keyword_list_path)
    else:
        print(f"Embedding {len(unique_keywords)} unique keywords...")
        keyword_embeds = embed_texts(
            unique_keywords,
            model_name=model_name,
            batch_size=batch_size,
        )
        torch.save(keyword_embeds, keyword_emb_path)
        write_json(unique_keywords, keyword_list_path)

    print("Computing keyword-column similarities...")

    # Both are normalized, so dot product is cosine similarity.
    sim_matrix = torch.matmul(keyword_embeds, column_embeds.T).numpy()

    keyword_to_top_columns = {}

    top_k = min(top_k, len(column_meta))

    for kw_idx, keyword in enumerate(unique_keywords):
        scores = sim_matrix[kw_idx]
        top_indices = np.argsort(-scores)[:top_k]

        top_columns = []
        for rank, col_idx in enumerate(top_indices, start=1):
            meta = column_meta[col_idx]
            top_columns.append({
                "rank": rank,
                "similarity": float(scores[col_idx]),
                "column_id": meta["column_id"],
                "table_id": meta["table_id"],
                "table_name": meta["table_name"],
                "column_name": meta["column_name"],
                "embedding_text": meta["embedding_text"],
            })

        keyword_to_top_columns[keyword] = top_columns

    # NOTE: the flat keyword-level file is intentionally NOT saved — it is fully
    # subsumed by the question-level file below (the only thing downstream reads).

    # Save question-level result
    question_level_results = {}

    for qid, rec in question_keywords.items():
        q_keywords = rec.get("keywords", [])

        question_level_results[qid] = {
            "question_id": rec.get("question_id", qid),
            "question": rec.get("question", ""),
            "keywords": q_keywords,
            "keyword_column_retrieval": {
                kw: keyword_to_top_columns.get(kw, [])
                for kw in q_keywords
            }
        }

    question_topk_path = f"{out_dir}/question_keywords_top{top_k}_columns.json"
    write_json(question_level_results, question_topk_path)
    print(f"Saved question-level keyword-column retrieval to: {question_topk_path}")

    return keyword_to_top_columns, question_level_results




# ============================================================
# Entry point
# ============================================================

def build_keyword_column_similarity(
    paths: "P.Paths",
    embedding_model_name: str = "WhereIsAI/UAE-Large-V1",
    llm_model: str = "gpt-4.1",
    batch_size: int = 64,
    top_k: int = 100,
    limit: int = 0,
    force_regenerate_keywords: bool = False,
    force_recompute_column_embeddings: bool = False,
    force_recompute_keyword_embeddings: bool = False,
):
    """Run stage 1 end to end for one dataset.

    limit > 0 keeps only the first N questions, which is what the smoke test
    uses to bound the number of LLM calls.
    """
    dev = read_json(str(paths.dev))
    tables = read_json(str(paths.tables))

    if limit and limit > 0:
        dev = dev[:limit]
        print(f"[stage1] limited to the first {len(dev)} questions")

    out_dir = str(paths.out_dir)
    create_directory(out_dir)
    keyword_path = os.path.join(out_dir, "question_keywords.json")

    # 1. Decompose each question into keyphrases (the only LLM call here).
    question_keywords = extract_keywords_for_dev(
        dev=dev,
        out_path=keyword_path,
        model=llm_model,
        force_regenerate=force_regenerate_keywords,
    )

    # 2. Embed the column corpus (cached).
    column_ids, column_meta, column_embeds = get_or_build_column_embeddings(
        tables=tables,
        out_dir=out_dir,
        model_name=embedding_model_name,
        batch_size=batch_size,
        force_recompute=force_recompute_column_embeddings,
    )
    print(f"Column embedding shape: {tuple(column_embeds.shape)}")

    # 3. Retrieve the top-k columns for every keyphrase.
    keyword_to_top_columns, question_level_results = retrieve_topk_columns_for_keywords(
        question_keywords=question_keywords,
        column_meta=column_meta,
        column_embeds=column_embeds,
        out_dir=out_dir,
        model_name=embedding_model_name,
        batch_size=batch_size,
        top_k=top_k,
        force_recompute_keyword_embeddings=force_recompute_keyword_embeddings,
    )

    return {
        "question_keywords": question_keywords,
        "column_ids": column_ids,
        "column_meta": column_meta,
        "keyword_to_top_columns": keyword_to_top_columns,
        "question_level_results": question_level_results,
        "out_dir": out_dir,
    }


def parse_args():
    parser = argparse.ArgumentParser(
        description="Stage 1: keyphrase extraction + keyphrase-column retrieval.")
    P.add_arguments(parser)
    parser.add_argument("--top-k", type=int, default=100,
                        help="Columns retrieved per keyphrase. Also the N in the "
                             "question_keywords_top{N}_columns.json file name.")
    parser.add_argument("--embedding-model", type=str, default="WhereIsAI/UAE-Large-V1",
                        help="Sentence encoder used for columns and keyphrases.")
    parser.add_argument("--llm-model", type=str, default="gpt-4.1",
                        help="LLM used for keyphrase extraction.")
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--limit", type=int, default=0,
                        help="Only process the first N questions (0 = all). "
                             "Use it to bound LLM cost in a smoke test.")
    parser.add_argument("--force-regenerate-keywords", action="store_true")
    parser.add_argument("--force-recompute-column-embeddings", action="store_true")
    parser.add_argument("--force-recompute-keyword-embeddings", action="store_true")
    return parser.parse_args()


if __name__ == "__main__":
    a = parse_args()
    build_keyword_column_similarity(
        P.from_args(a),
        embedding_model_name=a.embedding_model,
        llm_model=a.llm_model,
        batch_size=a.batch_size,
        top_k=a.top_k,
        limit=a.limit,
        force_regenerate_keywords=a.force_regenerate_keywords,
        force_recompute_column_embeddings=a.force_recompute_column_embeddings,
        force_recompute_keyword_embeddings=a.force_recompute_keyword_embeddings,
    )
